---
title: "AGNES clustering on aggregated VisitsSummary:get dataset"
output:
  html_document:
    code_folding: hide
editor_options: 
  chunk_output_type: inline
---

```{r}
f <- "./data/os-aggregates_2017-10-02-2018-04-14.RData"
if(!exists("ag")) load(f)
rm(f)
```
```{r}
#remove useless variables:
va.useless <- "nb_hits_following_search"
va <- unlist(sapply(ag,function(x) lapply(x,names)))
va <- data.frame(sub("\\d+$","",names(va)),va)
rownames(va) <- paste(va[,1],va[,2],sep=".")
va <- rownames(va)
va <- va[grep(va.useless,va)]
invisible(lapply(strsplit(va,"\\."),function(x)
  ag[[x[1]]][[x[2]]][,x[3]] <<- NULL))
rm(va.useless)
```

```{r}

preparedata <- function(module,method,outliers,va.rem,va.set,stand) {
  
  if (missing(va.rem)) va.rem <- NULL
  if (missing(va.set)) va.set <- NULL
  if (missing(stand)) stand <- T
  
  g <- ag[[module]][[method]]
  if (!is.null(g$label))
    g <- g[order(g$date,g$label),]
  else
    g <- g[order(g$date),]
  
  if (is.null(va.set))
    g <- ag[[module]][[method]][,which(!names(ag[[module]][[method]]) %in% va.rem)]
  else
    g <- ag[[module]][[method]][,which(names(ag[[module]][[method]]) %in% va.set)]
  
  g <- na.omit(g)
  if (!is.null(outliers))
    g <- g[-outliers,] #remove outliers
  rownames(g) <- 1:nrow(g)
 
  #filter on numeric variables
  g0 <- g[,which(sapply(names(g),function(x) is.numeric(g[,x])))]
  va <- names(g0)
  
  if (stand) g0 <- scale(g0)
  g0 <- setNames(g0,va)
  
  attr(g0,"lib") <- paste(module,method,sep=":")
  
  return(g0)
  
}

getCluster.ward <- function(dat,n) {
  
  #clustering
  
  d <- dist(dat, method = "euclidean")
  suppressMessages(H.fit <- hclust(d, method="ward"))
  groups <- cutree(H.fit, k=n)
  
  # plot(H.fit) # display dendogram
  # rect.hclust(H.fit, k=n, border="red")
  
  suppressPackageStartupMessages(require(factoextra))
  print(fviz_dend(H.fit,cex=0.6,k=n,
                  main="Ward hierarchichal clustering (euclidean distance)", sub=attributes(dat)$lib))
  print(fviz_cluster(list(data=dat,cluster=groups),main="Ward hierarchichal clustering (euclidean distance)"))
  print(colnames(dat))
  
  return(groups)
    
}

getCluster.agnes <- function(dat,n) {
  
  #clustering Agnes:
  suppressPackageStartupMessages(require(cluster))
  res <- agnes(dat,diss=FALSE,stand=T,metric="euclidian")
  groups <- cutree(res, k=n)
  
  # plot(res, main='Dendrogram') ## dendrogram
  # rect.hclust(res, k=n, border="red") 
  
  suppressPackageStartupMessages(require(factoextra))
  print(fviz_dend(res,cex=0.6,k=n,main="AGNES clustering",sub=attributes(dat)$lib))
  print(fviz_cluster(list(data=dat,cluster=groups),main="AGNES clustering"))
  print(colnames(dat))
  
  return(groups)
    
}

getCluster.kmeans <- function(dat,n) {
  
  #clustering K-Means:
  
  k <- kmeans(dat,n)
  
  # suppressPackageStartupMessages(require(cluster))
  # clusplot(dat, k$cluster, main="K-means clustering",color=TRUE, shade=TRUE,labels=2, lines=0)
  print(fviz_cluster(list(data=dat,cluster=k$cluster),main="K-means clustering"))
  print(colnames(dat))
  
  return(k)
    
}

```
***
#VisitsSummary:get aggregated dataset
```{r}
module <- "VisitsSummary"
method <- "get"
va.rem <- c("max_actions")
va.set <- c()
outliers <- c(8,89,9,44)
n.clusters <- 3

dat <- preparedata(module,method,outliers,va.rem,va.set,T)
ag0 <- na.omit(ag[[module]][[method]][-outliers,
                                      -which(names(ag[[module]][[method]]) %in% c("date",va.rem))])

g.ward <- getCluster.ward(dat,n.clusters)
cat("size of clusters:",table(g.ward))
cat("Characteristics of each cluster:")
lapply(1:3,function(x) summary(ag0[which(g.ward==x),]))

g.agnes <- getCluster.agnes(dat,n.clusters)
cat("size of clusters:",table(g.agnes))
cat("Characteristics of each cluster:")
lapply(1:3,function(x) summary(ag0[which(g.agnes==x),]))

g.kmeans <- getCluster.kmeans(dat,n.clusters)
cat("size of clusters:",g.kmeans$size)
cat("Characteristics of each cluster:")
lapply(1:3,function(x) summary(ag0[which(g.kmeans$cluster==x),]))

```

