---
title: "osstat"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=T}
library(flexdashboard)
suppressMessages(library(scatterD3))
library(plotly)
library(countrycode)
library(formattable)
library(slickR)
library(svglite)
library(dplyr)
load("data/d.RData")
load("data/refCountry.RData")
```

Countries
===================================== 

Row
-----------------------------------------------------------------------

### Days

```{r}
data <- d[["UserCountry"]][["getCountry"]]
begin <- min(data$date)
value <- max(data$date)-begin
valueBox(value, caption=paste0("Days (from ",begin,")"), icon = "fa-calendar")
```

### Countries

```{r}
value <- length(unique(data$metadata_code))
valueBox(value, icon = "fa-globe")

```

### Visits

```{r}
value <- paste0(round(sum(as.numeric(data$nb_visits))/1000)," k")
valueBox(value, icon = "fa-users")
```

### Actions

```{r}
value <- paste0(round(sum(as.numeric(data$nb_actions))/1000)," k")
valueBox(value, icon = "fa-dot-circle-o")
```

Row
-----------------------------------------------------------------------

### Traffic by Country

```{r}

df <- d[["UserCountry"]][["getCountry"]]
df$ratio_uniq_v <- with(df,as.numeric(nb_uniq_visitors)/as.numeric(nb_visits))

df.sum <- setNames(
  aggregate(cbind(as.numeric(nb_visits), as.numeric(nb_actions))~metadata_code,data=df, sum),
  c("country","nb_visits","nb_actions")
)
df.mean <- setNames(
  aggregate(cbind(ratio_uniq_v)~metadata_code,data=df, mean),
  c("country","ratio_uniq_v")
)
df <- merge(df.sum,df.mean,by=c("country"))

clusters <- scale(df[,c("nb_visits","nb_actions")])
fit <- kmeans(clusters,3)
centers <- as.data.frame(fit$centers)
centers$score <- with(centers,nb_visits+nb_actions)
df$cluster <- fit$cluster
df$cluster <- order(-centers$score)[df$cluster]

df$ratio_visits <- percent(with(df, nb_visits/sum(nb_visits)),digits=1)
df$ratio_actions <- percent(with(df, nb_actions/sum(nb_actions)),digits=1)
df$score <- with(df, (ratio_visits+ratio_actions)/2)

df <- merge(x=df,y=refCountry,by.x="country",by.y="code")

# first scatter plot
tooltips <- paste("<b>",df$lib,"</b><br/>nb visits:",df$nb_visits,"<br/>nb actions:",df$nb_actions)
s1 <- scatterD3(data=df, x=nb_visits, y=nb_actions, point_opacity=0.5, hover_size=4, hover_opacity=1, xlab="nb visits", ylab="nb actions", tooltip_text=tooltips)
htmlwidgets::saveWidget(s1,'s1.html')

# second one
s2 <- scatterD3(data=df, x=nb_visits, y=nb_actions, point_opacity=0.5, col_var=cluster, hover_size=4, hover_opacity=1, lab=country, xlab="nb visits", ylab="nb actions", col_lab="cluster", tooltip_text=tooltips)
htmlwidgets::saveWidget(s2,'s2.html')

# pie chart
p1 <- plot_ly(aggregate(score~cluster,df,sum), labels=~paste0("cluster ",cluster), values=~round(score*100), type='pie',
              showlegend=T,
              insidetextfont = list(color = '#FFFFFF'),
              marker = list(colors = c("lightgreen","lightcoral","lightblue"),
                            line = list(color = '#FFFFFF', width = 1))
) %>%
  layout(showlegend=T, title="part of traffic by country cluster")
htmlwidgets::saveWidget(p1,'p1.html')

# table
data <- df[order(-df$score),c("lib","cluster","score")]
data$rank <- 1:nrow(data)
data$score <- percent(data$score,digits=1)
data <- setNames(data,c("country","cluster","score","rank"))
t1 <- as.datatable(
  formattable(
    data,
    list(
      cluster = formatter("span", style = x ~ ifelse(x == 1, 
                                                     style(color = "orange", font.weight = "bold"), NA)),
      score=color_bar("lightblue"),
      rank = formatter("span", x~paste0("#",x))
    )
  ),
  rownames=F, class = "compact order-column hover", filter="top",
  options=list(columnDefs=list(list(className='dt-center',targets=c(1,3))))
) %>%
  DT::formatStyle(c("rank"),fontWeight="bold")
htmlwidgets::saveWidget(t1,'t1.html')

# geo map
g <- list(
  showframe = F,
  showcoastlines = T,
  projection = list(type = 'Mercator')
)
l <- list(color = toRGB("grey"), width = 0.5)
m1 <-  plot_geo(df) %>%
  add_trace(
    z=~round(score*100,1),
    locations=~countrycode(as.vector(country),origin="iso2c",destination="iso3c"),
    text=~lib,
    marker = list(line = l),
    colors='Blues'
  ) %>%
  layout(geo=g, title="traffic by country area") %>%
  colorbar(title = '% of global traffic')
htmlwidgets::saveWidget(m1,'m1.html')

# bar chart:

data <- df[df$cluster==1,]
data$ratio_uniq_v <- round(data$ratio_uniq_v*100)
b1 <- plot_ly(
  x=round(data$ratio_uniq_v), y=as.character(data$lib), name="cluster #1",
  type="bar", orientation="h", marker=list(color="lightgreen")
) %>%
  layout(
    margin = list(l=100, b=100)
    ) 

data <- df[df$cluster==2,]
data$ratio_uniq_v <- round(data$ratio_uniq_v*100)
b2 <- plot_ly(
  x=round(data$ratio_uniq_v), y=as.character(data$lib), name="cluster #2",
  type="bar", orientation="h", marker=list(color="lightcoral")
) %>%
  layout(
    margin = list(l=100)
  )

b <- subplot(b1,b2) %>%
  layout(title="part of unique visitors on daily visits for clusters #1 & #2")

htmlwidgets::saveWidget(b,'b.html')

# carousel to embed all the charts
slickR(c(paste0(readLines('s1.html'),collapse='\n'),
         paste0(readLines('s2.html'),collapse='\n'),
         paste0(readLines('p1.html'),collapse='\n'),
         paste0(readLines('t1.html'),collapse='\n'),
         paste0(readLines('m1.html'),collapse='\n'),
         paste0(readLines('b.html'),collapse='\n')),
       slideId = "countries",
       slideIdx = list(1:6),
       slideType = "iframe",
       slickOpts = list(dots=T),
       height='500px',width='100%')

```

Visits summary
===================================== 
```{r}
growth <- function(v) {
  growth0 <- function(x)x/lag(x)-1  
  l <- lowess(v)
  res <- round(growth0(c(l$y[1],l$y[length(l$y)]))*100)
  res <- res[2]
  return(res)
}
```

Row
-----------------------------------------------------------------------

### Days

```{r}
data <- d[["VisitsSummary"]][["get"]]
data <- data[order(data$date),]
begin <- min(data$date)
value <- max(data$date)-begin
valueBox(value, caption=paste0("Days (from ",begin,")"), icon = "fa-calendar")
```

### Visits (Average Growth Rate)

```{r}
data$nb_visits <- as.numeric(as.character(data$nb_visits))
value <- growth(data$nb_visits)
valueBox(paste0(value," %"), icon = "fa-users", color=ifelse(value>0,"success","warning"))
```

### Unique visitors (AGR)

```{r}
data$nb_uniq_visitors <- as.numeric(as.character(data$nb_uniq_visitors))
value <- growth(data$nb_uniq_visitors)
valueBox(paste0(value," %"), icon = "fa-user-plus", color=ifelse(value>0,"success","warning"))
```

### Actions (AGR)

```{r}
data$nb_actions <- as.numeric(as.character(data$nb_actions))
value <- growth(data$nb_actions)
valueBox(paste0(value," %"), icon = "fa-dot-circle-o", color=ifelse(value>0,"success","warning"))
```

### Average time on site (AGR)

```{r}
data$avg_time_on_site <- as.numeric(as.character(data$avg_time_on_site))
value <- growth(data$avg_time_on_site)
valueBox(paste0(value," %"), icon = "fa-clock-o", color=ifelse(value>0,"success","warning"))
```

### Bounce rate (AGR)

```{r}
data$bounce_rate <- as.numeric(gsub("%","",as.character(data$bounce_rate)))
value <- growth(data$bounce_rate)
valueBox(paste0(value," %"), icon = "fa-futbol-o", color=ifelse(value>0,"warning","success"))
```

Row
-----------------------------------------------------------------------

```{r}

#visits chart (unadjusted):
vs_1 <- plot_ly(data, x=~date, y=~round(nb_visits), type="scatter", mode="lines", line=list(color="royalblue")) %>%
  layout(title = "number of visits (non adjusted)",
         xaxis = list(title = "days"),
         yaxis = list (title = "visits"))

htmlwidgets::saveWidget(vs_1,'vs_1.html')

#visits chart (smoothed):
l <- lowess(data$nb_visits)
l$x <- data$date
l<- as.data.frame(l)
vs_2 <- plot_ly(x=data$date, y=round(data$nb_visits), type="scatter", mode="lines", line=list(color="lightblue"), name="unadjusted") %>%
  add_trace(y=round(l$y),line=list(color="red"), name="smoothed") %>%
  layout(title = "number of visits",
         yaxis = list (title = "visits"))

htmlwidgets::saveWidget(vs_2,'vs_2.html')

#unique visitors:
l <- lowess(data$nb_uniq_visitors)
l$x <- data$date
l<- as.data.frame(l)
vs_3 <- plot_ly(x=data$date, y=round(data$nb_uniq_visitors), type="scatter", mode="lines", line=list(color="lightblue"), name="unadjusted") %>%
  add_trace(y=round(l$y),line=list(color="red"), name="smoothed") %>%
  layout(title = "number of unique visitors",
         yaxis = list (title = "unique visitors"))

htmlwidgets::saveWidget(vs_3,'vs_3.html')

#actions:
l <- lowess(data$nb_actions)
l$x <- data$date
l<- as.data.frame(l)
vs_4 <- plot_ly(x=data$date, y=round(data$nb_actions), type="scatter", mode="lines", line=list(color="lightblue"), name="unadjusted") %>%
  add_trace(y=round(l$y),line=list(color="red"), name="smoothed") %>%
  layout(title = "number of actions",
         yaxis = list (title = "actions"))

htmlwidgets::saveWidget(vs_4,'vs_4.html')

#average time on site:
l <- lowess(data$avg_time_on_site)
l$x <- data$date
l<- as.data.frame(l)
vs_5 <- plot_ly(x=data$date, y=round(data$avg_time_on_site), type="scatter", mode="lines", line=list(color="lightblue"), name="unadjusted") %>%
  add_trace(y=round(l$y),line=list(color="red"), name="smoothed") %>%
  layout(title = "average time on site",
         yaxis = list (title = "time on site (avg)"))

htmlwidgets::saveWidget(vs_5,'vs_5.html')

#bounce rate:
l <- lowess(data$bounce_rate)
l$x <- data$date
l<- as.data.frame(l)
vs_6 <- plot_ly(x=data$date, y=round(data$bounce_rate), type="scatter", mode="lines", line=list(color="lightblue"), name="unadjusted") %>%
  add_trace(y=round(l$y),line=list(color="red"), name="smoothed") %>%
  layout(title = "bounce rate",
         yaxis = list (title = "bounce rate"))

htmlwidgets::saveWidget(vs_6,'vs_6.html')


# carousel to embed all the charts
slickR(c(paste0(readLines('vs_1.html'),collapse='\n'),
         paste0(readLines('vs_2.html'),collapse='\n'),
         paste0(readLines('vs_3.html'),collapse='\n'),
         paste0(readLines('vs_4.html'),collapse='\n'),
         paste0(readLines('vs_5.html'),collapse='\n'),
         paste0(readLines('vs_6.html'),collapse='\n')),
       slideId = "vs",
       slideIdx = list(1:6),
       slideType = "iframe",
       slickOpts = list(dots=T),
       height='500px',width='100%')

```

Visit frequency
===================================== 

[osstat-visitfreq.html#visit-frequency]

Social
===================================== 

[osstat-social.html#social]

Campaign efficiency
=====================================
