---
title: "osstat"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=T}
library(flexdashboard)
suppressMessages({
  library(scatterD3)
  library(ggplot2)
})
library(plotly)
library(countrycode)
library(formattable)
library(slickR)
library(svglite)
library(dplyr)
load("data/d.RData")
load("data/refCountry.RData")
```

Countries
===================================== 

Visits summary
===================================== 

Visit frequency
===================================== 

Social
=====================================

Campaign efficiency
=====================================

```{r}
growth <- function(v) {
  growth0 <- function(x)x/lag(x)-1  
  l <- lowess(v)
  res <- round(growth0(c(l$y[1],l$y[length(l$y)]))*100)
  res <- res[2]
  return(res)
}
```

Row
-----------------------------------------------------------------------

### Days

```{r}
data <- d[["VisitsSummary"]][["get"]]
data <- data[order(data$date),]
data <- data[data$date>"2017-04-10",]
begin <- min(data$date)
value <- max(data$date)-begin
valueBox(value, caption=paste0("Days (from ",begin,")"), icon = "fa-calendar", color="brown")
```

### Visits BEFORE (Average Growth Rate)

```{r}
data0 <- data
data <- data[as.Date(data$date)<as.Date("2017-05-01"),]
#data$nb_visits_returning <- as.numeric(as.character(data$nb_visits_returning))
data$nb_visits <- as.numeric(as.character(data$nb_visits))
#value <- growth(data$nb_visits_returning)
value <- growth(data$nb_visits)
valueBox(paste0(value," %"), icon = "fa-users", color="primary")
```


### Actions BEFORE (AGR)

```{r}
#data$nb_actions_returning <- as.numeric(as.character(data$nb_actions_returning))
data$nb_actions <- as.numeric(as.character(data$nb_actions))
#value <- growth(data$nb_actions_returning)
value <- growth(data$nb_actions)
valueBox(paste0(value," %"), icon = "fa-dot-circle-o", color="primary")
data <- data0
```


### Visits AFTER (Average Growth Rate)

```{r}
# data0 <- data
# data <- data[as.Date(data$date)>as.Date("2017-05-07"),]
#data$nb_visits_returning <- as.numeric(as.character(data$nb_visits_returning))
data$nb_visits <- as.numeric(as.character(data$nb_visits))
#value <- growth(data$nb_visits_returning)
value <- growth(data$nb_visits)
valueBox(paste0(value," %"), icon = "fa-users", color="info")
```


### Actions AFTER (AGR)

```{r}
#data$nb_actions_returning <- as.numeric(as.character(data$nb_actions_returning))
data$nb_actions <- as.numeric(as.character(data$nb_actions))
#value <- growth(data$nb_actions_returning)
value <- growth(data$nb_actions)
valueBox(paste0(value," %"), icon = "fa-dot-circle-o", color="info")
data <- data0
```


Row
-----------------------------------------------------------------------

```{r}
#BEFORE

#data_vs <- d[["VisitsSummary"]][["get"]]
data_vf <- d[["VisitFrequency"]][["get"]]
data_vf <- data_vf[order(data_vf$date),]

data_vf0 <- data_vf
#data_vs <- data_vs[data_vs$date>"2017-04-10" & data_vs$date<"2017-05-01",]
data_vf <- data_vf[data_vf$date>"2017-04-10" & data_vf$date<"2017-05-01",]

data0 <- data
data <- data[data$date<"2017-05-01",]

#!!!!
# tmp <- data
# data <- data_vs
# data_vs <- data

getNewvsRet <- function(vr, vs) {
  
  #data_vs[,c(vs)] <- as.numeric(as.character(data_vs[,c(vs)]))
  
  d_ret <- data_vf
  d_ret$val <- as.numeric(as.character(d_ret[,c(vr)]))/as.numeric(as.character(data[,c(vs)]))
  l <- lowess(d_ret$val)
  d_ret$val <- l$y
  d_ret$type <- "Returning"
  d_ret <- d_ret[,c("date","type","val")]
  
  d_new <- d_ret
  d_new$val <- abs(1-d_new$val)
  d_new$type <- "New"
  d_new <- d_new[,c("date","type","val")]
  
  d_m <- rbind(d_new,d_ret)
  d_m<-d_m[order(d_m$date),]
  
  return(d_m)
  
}

#stacked area chart (visits)

d_m <- getNewvsRet("nb_visits_returning","nb_visits")

ce_1 <- ggplot(d_m, aes(x=date,y=val,group=type,fill=type)) + geom_area(position="fill") +
  ggtitle("visits from visitors BEFORE (Returning vs New)") +
  scale_fill_discrete(name = "visitors") +
  labs(x="",y="") +
  scale_fill_brewer(palette="PiYG")
  
# d_m <- getNewvsRet("nb_uniq_visitors_returning","nb_uniq_visitors")
# 
# vf_2 <- ggplot(d_m, aes(x=date,y=val,group=type,fill=type)) + geom_area(position="fill") +
#   ggtitle("unique visitors (Returning vs New)") +
#   scale_fill_discrete(name = "unique visitors") +
#   labs(x="",y="") +
#   scale_fill_brewer(palette="PRGn")

d_m <- getNewvsRet("nb_actions_returning","nb_actions")

ce_2 <- ggplot(d_m, aes(x=date,y=val,group=type,fill=type)) + geom_area(position="fill") +
  ggtitle("actions BEFORE (from Returning vs New visitors)") +
  scale_fill_discrete(name = "actions") +
  labs(x="",y="") +
  scale_fill_brewer(palette="Set3")

# d_m <- getNewvsRet("avg_time_on_site_returning","avg_time_on_site")

# vf_4 <- ggplot(d_m, aes(x=date,y=val,group=type,fill=type)) + geom_area(position="fill") +
#   ggtitle("average time on site (from Returning vs New visitors)") +
#   scale_fill_discrete(name = "average time") +
#   labs(x="",y="") +
#   scale_fill_brewer(palette="BrBG")

#5
# data_vs$bounce_rate <- as.numeric(gsub("%","",as.character(data_vs$bounce_rate)))
# d_m <- getNewvsRet("bounce_rate_returning","bounce_rate")
# 
# vf_5 <- ggplot(d_m, aes(x=date,y=val,group=type,fill=type)) + geom_area(position="fill") +
#   ggtitle("bounce rate (from Returning vs New visitors)") +
#   scale_fill_discrete(name = "bounce rate") +
#   labs(x="",y="") +
#   scale_fill_brewer(palette="Set2")

data_vf <- data_vf0
data <- data0

# AFTER
data <- data[data$date>"2017-05-07",]
data_vf <- data_vf[data_vf$date>"2017-05-07",]

d_m <- getNewvsRet("nb_visits_returning","nb_visits")

ce_3 <- ggplot(d_m, aes(x=date,y=val,group=type,fill=type)) + geom_area(position="fill") +
  ggtitle("visits from visitors AFTER (Returning vs New)") +
  scale_fill_discrete(name = "visitors") +
  labs(x="",y="") +
  scale_fill_brewer(palette="PiYG")

d_m <- getNewvsRet("nb_actions_returning","nb_actions")

ce_4 <- ggplot(d_m, aes(x=date,y=val,group=type,fill=type)) + geom_area(position="fill") +
  ggtitle("actions AFTER (from Returning vs New visitors)") +
  scale_fill_discrete(name = "actions") +
  labs(x="",y="") +
  scale_fill_brewer(palette="Set3")

toSVG <- list(
  xmlSVG({show(ce_1)},standalone=T),
  xmlSVG({show(ce_2)},standalone=T),
  xmlSVG({show(ce_3)},standalone=T),
  xmlSVG({show(ce_4)},standalone=T)
)

s.in=sapply(toSVG,function(sv){paste0("data:image/svg+xml;utf8,",as.character(sv))})
slickR(s.in,slideId = 'ce',slickOpts = list(dots=T), height = 500,width = '100%')


```

