---
title: "Our statistics - web traffic indicators"
output:
  html_document: default
---

<p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>

```{r setup, include=TRUE, echo=FALSE}
suppressMessages(suppressWarnings(library(highcharter)))
library(ISOcodes)
suppressMessages(suppressWarnings(library(dplyr)))
if (!exists("d")) load("data/d.RData")
v <- d[["Live"]][["getLastVisitsDetails:Visits"]]
```


```{r echo=FALSE}

c_dailyvisits <- function(df, lib) {
  
  l <- lowess(df$nb_visits)
  l$x <- df$date
  l<- setNames(as.data.frame(l),c("label","value"))
  l$value <- round(l$value)
  
  highchart() %>%
    hc_exporting(enabled=T) %>%
    hc_title(text="Number of visits") %>%
    hc_subtitle(text=lib) %>%
    hc_xAxis(categories=data$date, 
             title=list(text="")) %>%
    hc_yAxis(title=list(text="number of visits (daily)")) %>%
    hc_add_series(name="visits (unadjusted)", data=data$nb_visits) %>%
    hc_add_series(name="visits (trend)", data=l$value) %>%
    hc_add_theme(hc_theme_elementary())
  
}

data <- d[["VisitsSummary"]][["get"]]
data <- data[order(data$date),]
data <- data[data$date>="2017-03-01" & data$date<="2017-05-31",]
data$nb_visits <- as.numeric(data$nb_visits)

c_dv_3m <- c_dailyvisits(data,"in daily visits for 3 months")

data <- d[["VisitsSummary"]][["get"]]
data <- data[order(data$date),]
data <- data[data$date>="2016-01-01" & data$date<="2017-05-31",]
data$nb_visits <- as.numeric(data$nb_visits)

c_dv_18m <- c_dailyvisits(data,"in daily visits since January 2016")


```

<table width="100%"><tr width="100%"><td width="50%">

```{r echo=FALSE}
c_dv_3m
```

</td><td width="50%">

```{r echo=FALSE}
c_dv_18m
```

</td></tr></table>
<p/><hr>

```{r echo=FALSE}

v$visitorType <- as.character(v$visitorType)
visitorType <- setNames(as.data.frame(table(v$visitorType)),c("visitorType","number"))

c_visitors_vs <- highchart() %>%
  hc_exporting(enabled=T) %>%
  hc_chart(type="pie") %>%
  hc_title(text="New visitors vs Returning visitors") %>%
  hc_subtitle(text="in cumulated number of visits for 3 months") %>%
  hc_series(
    list(
      data = list(
        list(
          name=as.character(visitorType$visitorType[1]),
          y=visitorType$number[1],
          sliced=T, selected=T),
        list(
          name=as.character(visitorType$visitorType[2]),
          y=visitorType$number[2])
      )
    )
  ) %>%
  hc_tooltip(
    headerFormat="",
    pointFormat="{point.y}") %>%
  hc_add_theme(hc_theme_elementary())

rm(visitorType)

#next chart

v$visitDuration <- as.numeric(as.character(v$visitDuration))
vd.new <- v[v$visitDuration>0 & v$visitDuration<=300 & v$visitorType=="new",]$visitDuration
vd.ret <- v[v$visitDuration>0 & v$visitDuration<=300 & v$visitorType=="returning",]$visitDuration
vd.breaks <- seq(from=0,to=300,by=6)
vd.c.new <- table(cut(x=vd.new,breaks=vd.breaks,include.lowest=F,right=F))
vd.c.ret <- -table(cut(x=vd.ret,breaks=vd.breaks,include.lowest=F,right=F))
names(vd.c.new) <- sub(")","[",names(vd.c.new))
names(vd.c.new) <- sub(",",", ",names(vd.c.new))
names(vd.c.new)[1] <- sub("\\[0","]0",names(vd.c.new)[1])

series <- list(
    list(data=vd.c.new,name="new visitors"),
  list(data=vd.c.ret,name="returning visitors")
)

xaxis <- list(
  title=list(text="visits duration in seconds interval"),
  gridLineWidth=1,
  categories = names(vd.c.new),
  reversed = FALSE, tickInterval = 1,
  labels = list(step = 5))

maxpop <- max(max(vd.c.new),max(vd.c.ret))

c_vd_visitor <- highchart() %>%
  hc_exporting(enabled=T) %>%
  hc_chart(type = "bar") %>%
  hc_title(text="Visits duration according visitor type") %>%
  hc_subtitle(text="in cumulated number of visits for 3 months") %>%
  hc_add_series_list(series) %>% 
  hc_plotOptions(
    series = list(stacking = "normal"),
    bar = list(groupPadding = 0, pointPadding =  0, borderWidth = 0)
  ) %>% 
  hc_tooltip(shared = TRUE) %>%
  hc_yAxis(
    title=list(text="number of visits"),
    gridLineWidth=1,
    labels = list(
      formatter = JS("function(){ return Math.abs(this.value); }")
    ),
    tickInterval = 100,
    min = -maxpop,
    max = maxpop) %>%
  hc_xAxis(
    xaxis,
    rlist::list.merge(xaxis, list(opposite = TRUE, linkedTo = 0))
  ) %>% 
  hc_tooltip(shared = FALSE,
             formatter = JS("function () { return '<b>' + this.series.name + '<br/>' + 'visits duration in ' + this.point.category + ' s</b><br/>' + 'number of visits: ' + Highcharts.numberFormat(Math.abs(this.point.y), 0);}")
  ) %>%
  hc_add_theme(hc_theme_elementary())

```

<table width="100%"><tr width="100%"><td width="33%">

```{r echo=FALSE}
c_visitors_vs
```

</td><td width="67%">

```{r echo=FALSE}
c_vd_visitor
```

</td></tr></table>
<p/><hr>

```{r echo=FALSE}

data <- data.frame(sort(table(v$deviceType),decreasing=T))
data$Var1 <- as.character(data$Var1)
data_1 <- setNames(
  data.frame(c("Desktop","Mobile"),
             c(sum(data[data$Var1=="Desktop",]$Freq),
             sum(data[data$Var1!="Desktop",]$Freq))),
  c("label","value")
)

suppressWarnings(
  c_dev_1 <- highchart() %>%
    hc_exporting(enabled=T) %>%
    hc_chart(type="pie") %>%
    hc_title(text="Visitors devices") %>%
    hc_subtitle(text="in cumulated number of visits for 3 months") %>%
    hc_series(
      list(
        data = list(
          list(
            name=as.character(data_1$label[1]),
            y=data_1$value[1],
            sliced=T, selected=T),
          list(
            name=as.character(data_1$label[2]),
            y=data_1$value[2])
        )
      )
    ) %>%
    hc_tooltip(
      headerFormat="",
      pointFormat="{point.y}") %>%
    hc_add_theme(hc_theme_elementary())
)

#next chart
data_2 <- subset(data,data$Var1 %in% c("Smartphone","Tablet","Phablet"))
data_2 <- rbind(data_2,
                setNames(
                  data.frame(
                  c("Others"),
                  sum(subset(data,!data$Var1 %in% c("Desktop","Smartphone","Tablet","Phablet"))$Freq)
                ),
                c("Var1","Freq")
                )
)

suppressWarnings(
  c_dev_2 <- highchart() %>%
    hc_exporting(enabled=T) %>%
    hc_title(text = "detail for mobiles") %>%
    hc_subtitle(text="in cumulated number of visits for 3 months") %>%
    hc_xAxis(categories = data_2$Var1) %>%
    hc_add_series(data_2, type="bar", name = "number of visits",
                  hcaes(name = Var1, y = Freq), showInLegend = T,
                  color="#FA8832") %>%
    hc_add_theme(hc_theme_elementary())
)

```

<table width="100%"><tr width="100%"><td width="50%">

```{r echo=FALSE}
c_dev_1
```

</td><td width="50%">

```{r echo=FALSE}
c_dev_2
```

</td></tr></table>
<p/><hr>

```{r echo=FALSE}

freqdis <- function() {

  v$visitDuration <- as.numeric(as.character(v$visitDuration))

  duration <- v$visitDuration/60
  breaks <- seq(0,max(duration),by=1)
  duration.cut = cut(duration, breaks, right=FALSE)
  duration.freq = table(duration.cut)

  duration.cumfreq <- cumsum(duration.freq)
  duration.cumfreq = cbind(duration.cumfreq/tail(duration.cumfreq,1))

  highchart() %>%
    hc_exporting(enabled=T) %>%
    hc_title(text="Cumulated frequency of Visits duration") %>%
    hc_subtitle(text="based on visits for 3 months") %>%
    hc_chart(type="line") %>%
    hc_yAxis(
      title = list(text = "percent")) %>%
    hc_xAxis(
      categories = head(rownames(duration.cumfreq),60),
      title = list(text = "minutes"),
      plotBands=list(
        list(
          color="#FAD1A8",
          from=0,
          to=4
        )
      )
      ) %>%
    hc_series(
      list(
        name = "visits duration",
        data = setNames(head(duration.cumfreq[,1],60)*100,NULL)
      )
    ) %>%
    hc_tooltip(
      headerFormat="visits duration in <b>{point.key}</b> minutes<br>",
      pointFormat="up to <b>{point.y:.0f}</b> % of total visits") %>%
    hc_add_theme(hc_theme_elementary()) %>%
    hc_annotations(
      list(
        xValue=8,
        yValue=88,
        title= list(text="90 % of visits duration<br>are below 5 min")
      )
    )

}

freqdis()

```

<p/><hr>

```{r echo=FALSE}

referrerTypeName <- setNames(
  head(
    as.data.frame(
      sort(
        table(as.character(v$referrerTypeName)),
        decreasing=T)
    ),
    3),
  c("referrerTypeName","number")
)
referrerTypeName$referrerTypeName <- as.character(referrerTypeName$referrerTypeName)
referrerTypeName$referrerTypeName[1] <- paste0(
  as.character(referrerTypeName$referrerTypeName[1])," & social networks")

twitter <- v[grep("twitter|co$",v$referrerName, ignore.case=T),]
linkedin <- v[grep("linkedin",v$referrerName, ignore.case=T),]
facebook <- v[grep("facebook",v$referrerName, ignore.case=T),]

social <- nrow(twitter)+nrow(linkedin)+nrow(facebook)

t <- referrerTypeName[referrerTypeName$referrerTypeName=="Websites & social networks",]
t$number <- as.character(as.numeric(t$number)-social)
t$referrerTypeName <- "Websites"

t <- rbind(t,c("Social networks",as.character(social)))

referrerTypeName <- referrerTypeName[referrerTypeName$referrerTypeName!="Websites & social networks",]
referrerTypeName <- rbind(referrerTypeName,t)

referrerTypeName$number <- as.numeric(referrerTypeName$number)

suppressWarnings(
  c_entry_g <- highchart() %>%
    hc_exporting(enabled=T) %>%
    hc_chart(type="pie") %>%
    hc_title(text="Visitors entry mode") %>%
    hc_subtitle(text="in cumulated number of visits for 3 months") %>%
    hc_plotOptions(
      pie = list(
        dataLabels = list(
          enabled = TRUE,
          format="<b>{point.name}</b><br>{point.percentage:.0f} %"
        ),
        enableMouseTracking = T,
        distance=-30)
    ) %>%
    hc_series(
      list(
        data = list(
          list(
            name=as.character(referrerTypeName$referrerTypeName[3]),
            y=referrerTypeName$number[3],
            sliced=F, selected=F),
          list(
            name=as.character(referrerTypeName$referrerTypeName[2]),
            y=referrerTypeName$number[2],
            sliced=F, selected=F),
          list(
            name=as.character(referrerTypeName$referrerTypeName[1]),
            y=referrerTypeName$number[1],
            sliced=F, selected=F),
          list(
            name=as.character(referrerTypeName$referrerTypeName[4]),
            y=referrerTypeName$number[4],
            sliced=T, selected=T)
        )
      )
    ) %>%
    hc_tooltip(
      headerFormat="",
      pointFormat="{point.y}") %>%
    hc_add_theme(hc_theme_elementary())
)

#Social:

traffic_social <- setNames(data.frame(c("Twitter","Linked.in","Facebook"),
                                      c(nrow(twitter),nrow(linkedin),nrow(facebook))),
                           c("label","value"))

suppressWarnings(
  c_entry_s <- highchart() %>%
    hc_exporting(enabled=T) %>%
    hc_title(text = "Traffic from Social networks") %>%
    hc_subtitle(text="in cumulated number of visits for 3 months") %>%
    hc_xAxis(categories = traffic_social$label) %>%
    hc_add_series(traffic_social, type="bar", name = "number of visits",
                  hcaes(name = label, y = value), showInLegend = T,
                  color="#E46151") %>%
    hc_add_theme(hc_theme_elementary())
)

```

<table width="100%"><tr width="100%"><td width="50%">

```{r echo=FALSE}
c_entry_g
```

</td><td width="50%">

```{r echo=FALSE}
c_entry_s
```

</td></tr></table>
<p/><hr>

```{r echo=FALSE}

lc <- as.data.frame(
  t(
    table(v[v$languageCode!="",]$languageCode)
  ),
  stringAsFactors=F)
lc <- lc[lc$Freq!=0,]
lc$Var2 <- as.character(lc$Var2)
lc$Var1 <- sapply(strsplit(lc$Var2,"-"),"[",1)
lc <- setNames(aggregate(Freq~Var1,lc,sum),c("Var1","n"))

data("ISO_639_2")
lc <- merge(lc,ISO_639_2[,c("Alpha_2","Name")],by.x=c("Var1"),by.y=c("Alpha_2"))
lc <- lc[order(-lc$n),]
lc$Name <- gsub("(,|;).+","",lc$Name)

cs <- cumsum(lc$n/sum(lc$n))<0.96

suppressWarnings(
  highchart() %>%
    hc_exporting(enabled=T) %>%
    hc_title(text = "Visitors languages") %>%
    hc_subtitle(text="in cumulated number of visits for 3 months") %>%
    hc_plotOptions(
      pie = list(
        colorByPoint = TRUE, center = c('30%', '30%'),
        size = 120,
        dataLabels = list(
          enabled = T,
          format="<b>{point.name}</b><br>{point.percentage:.0f} %"
        )
      )
    ) %>%
    hc_xAxis(categories = lc[cs,]$Name) %>%
    hc_add_series(data = lc[cs,]$n, type="column", name = "top 20 visitors languages") %>%
    hc_add_series(
      data=setNames(
        data.frame(
          c(paste0("top ",nrow(lc[cs,])," languages"),
            paste0("others languages (",nrow(lc[!cs,]),")")),
          c(sum(lc[cs,]$n),sum(lc[!cs,]$n))
        ),
        c("category","value")
      ),
      type="pie",
      hcaes(name = category, y = value),
      name="number of visits") %>%
    hc_add_theme(hc_theme_elementary())
)

rm(lc,cs,ISO_639_2)

```

<p/><hr>

```{r echo=FALSE}

#mapdata <- get_data_from_map(download_map_data("custom/world"))

cc <- setNames(data.frame(t(table(v$countryCode)))[,c("Var2","Freq")],c("countryCode","nbVisits"))
cc$countryCode <- as.character(cc$countryCode)

c1 <- function() {
  hcmap(map = "custom/world", download_map_data=T, data=cc, joinBy=c("hc-key","countryCode"), value="nbVisits",
        name="number of visits") %>%
    hc_exporting(enabled=T) %>%
    hc_credits(enabled=F) %>%
    hc_title(text = "Visitors country") %>%
    hc_subtitle(text="in cumulated number of visits for 3 months") %>%
    hc_add_theme(hc_theme_elementary()) %>%
    hc_mapNavigation(enabled = TRUE)
}

cc10 <- head(cc[order(-cc$nbVisits),],10)
data("ISO_3166_1")
ISO_3166_1$Alpha_2 <- tolower(ISO_3166_1$Alpha_2)
m <- merge(x=cc10, y=ISO_3166_1, by.x="countryCode", by.y="Alpha_2")
cc10 <- m[order(-m$nbVisits),c("countryCode","Name","nbVisits")]

c2 <- function() {
  highchart() %>%
    hc_exporting(enabled=T) %>%
    hc_title(text = "top 10") %>% 
    hc_xAxis(categories = cc10$Name) %>%
    hc_add_series(cc10, type="bar", name = "number of visits",
                  hcaes(name = countryCode, y = nbVisits), showInLegend = T) %>%
    hc_add_theme(hc_theme_elementary())
}

```

<table width="100%"><tr width="100%"><td width="50%">

```{r echo=FALSE}
c1()
```

</td><td width="50%">

```{r echo=FALSE}
c2()
```

</td></tr></table>
<p/><hr>

```{r echo=FALSE}

vt <- d[["VisitTime"]][["getVisitInformationPerLocalTime"]]
vt <- vt[vt$date>=min(v$date),]
vt$nb_visits <- as.numeric(vt$nb_visits)
vt$nb_actions <- as.numeric(vt$nb_actions)

av <- aggregate(nb_visits~label,vt,sum)
av$label <- as.numeric(sub("h","",as.character(av$label)))
av <- av[order(av$label),]

c_vh_v <- highchart() %>%
  hc_exporting(enabled=T) %>%
  hc_title(text = "Visits hours") %>%
  hc_subtitle(text="in cumulated number of visits for 3 months") %>%
  hc_xAxis(categories = av$label) %>%
  hc_chart(polar=T) %>%
  hc_add_series(av, type="column", name = "number of visits",
                hcaes(name = label, y = nb_visits), showInLegend = T) %>%
  hc_add_theme(hc_theme_elementary())

vt_d <- d[["VisitTime"]][["getByDayOfWeek"]]
vt_d <- vt_d[vt_d$date>=min(v$date),]
vt_d$nb_visits <- as.numeric(vt_d$nb_visits)

av_d <- aggregate(nb_visits~label,vt_d,sum)
av_d$label <- as.character(av_d$label)
days <- c("Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday")
rownames(av_d) <- av_d$label
av_d <- av_d[days,]

c_av_d <- highchart() %>%
  hc_exporting(enabled=T) %>%
  hc_title(text = "Visits days") %>%
  hc_subtitle(text="in cumulated number of visits for 3 months") %>%
  hc_xAxis(categories = av_d$label) %>%
  hc_chart(polar=T) %>%
  hc_add_series(av_d, type="column", name = "number of visits",
                hcaes(name = label, y = nb_visits), showInLegend = T) %>%
  hc_add_theme(hc_theme_elementary())

```
<table width="100%"><tr width="100%"><td width="50%">

```{r echo=FALSE}
c_vh_v
```

</td><td width="50%">

```{r echo=FALSE}
c_av_d
```

</td></tr></table>
<p/><hr>

```{r echo=FALSE}

clean <- function(begin,end,agreg) {
  
  if (missing(agreg)) agreg <- T
  
  p <- d[["Actions"]][["getPageUrls"]]
  p <- p[p$date>=begin & p$date<=end,]
  p$label <- as.character(p$label)
  p$cat1 <- sub("\\?.*$","",p$label) 
  p$cat1 <- sub("^/","",p$cat1)
  p$cat1 <- gsub("-"," ",p$cat1)
  p$nb_hits <- as.numeric(p$nb_hits)
  
  if (agreg)
    pa <- aggregate(nb_hits~cat1,p,sum) 
  else
    pa <- p
  
  wl <- c("bank interest rates loans","financing and investment dynamics","macro economic indicators","inflation rates","bank interest rates deposits","competitiveness indicators","banks balance sheet deposits","banks balance sheet loans","macroeconomic scoreboard","securities quoted shares","external sector","international investment position","securities debt securities","investment funds assets","external debt","financial account","investment funds liabilities","investment funds policies","investment funds types","reserve assets")
  pa$sel <- 0
  pa[pa$cat1 %in% wl,]$sel <- 1
  pa <- pa[order(-pa$nb_hits),]
  
  cat <- c("Bank interest rates","Banks balance sheet","Competitiveness indicators","External sector","Inflation rates","Investment funds","Macro economic indicators","Securities","Financing and investment dynamics")
  cat <- tolower(cat)
  
  t<-sapply(cat,function(x) grep(x,pa$cat1))
  
  pa$cat <- ""
  for (i in 1:length(t))
    pa[t[[i]],]$cat <- names(t)[i]

  pa[pa$cat1=="macroeconomic scoreboard",]$cat <- "macro economic indicators"
  pa[pa$cat1=="international investment position",]$cat <- "external sector"
  pa[pa$cat1=="external debt",]$cat <- "external sector"
  pa[pa$cat1=="financial account",]$cat <- "external sector"
  pa[pa$cat1=="reserve assets",]$cat <- "external sector"
  
  pa_sel <- pa[pa$sel==1,]
  if (agreg)
    pa_sel <- aggregate(nb_hits~cat,pa_sel,sum)[,c("cat","nb_hits")]
  else {
    pa_sel <- aggregate(nb_hits~date+cat,pa_sel,sum)
    pa_sel <- pa_sel[order(pa_sel$date),]
  }
  
  return(pa_sel)
  
}

p_a <- clean(begin="2017-03-01", end="2017-05-31",agreg=T)

highchart() %>%
  hc_exporting(enabled=T) %>%
  hc_title(text = "actions by content") %>%
  hc_subtitle(text="in cumulated number of actions for 3 months") %>%
  hc_add_series(p_a, type="treemap", name = "number of actions",
                hcaes(x = cat, value = nb_hits, color=order(nb_hits)), showInLegend = F, colorByPoint=T)


```

<p/><hr>

```{r echo=FALSE}

begin <- "2017-03-01"
end <- "2017-05-31"

p <- clean(begin,end,agreg=F)

suppressMessages(require(viridis))

fntltp <- JS("function(){
  return this.series.xAxis.categories[this.point.x] + ' ' +  this.series.yAxis.categories[this.point.y] + ':<br>' +
  Highcharts.numberFormat(this.point.value, 0) + ' hits';
}")

hchart(p, "heatmap", hcaes(x = as.character(date), y = cat, value = nb_hits)) %>% 
  hc_exporting(enabled=T) %>%  
  hc_colorAxis(stops = color_stops(10, rev(inferno(10))),
               type = "logarithmic") %>% 
  hc_yAxis(reversed = TRUE, offset = 0, tickLength = 0,
           gridLineWidth = 0, minorGridLineWidth = 0,
           title=list(text="")
  ) %>% 
  hc_tooltip(formatter = fntltp) %>%
  hc_xAxis(
    title=list(text=paste0("from ",begin," to ",end)),
    labels=list(enabled=F), tickLength=0
    ) %>%
  hc_title(text = "actions by content") %>%
  hc_subtitle(text="in daily actions for 3 months") %>%
  hc_legend(layout = "vertical", verticalAlign = "top",
            align = "right", valueDecimals = 0)


```


